"""Initial migration: create all tables

Revision ID: 480e18c0374d
Revises:
Create Date: 2025-10-14 09:40:42.328742

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sys
from pathlib import Path

# Add parent directory to path to import GUID type
sys.path.insert(0, str(Path(__file__).resolve().parents[2]))
from src.database import GUID


# revision identifiers, used by Alembic.
revision: str = '480e18c0374d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('role', sa.Enum('admin', 'manager', 'user', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('channels',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('active', 'inactive', 'suspended', name='channelstatus'), nullable=False),
    sa.Column('business_type', sa.Enum('basic', 'high_value', 'pending_signup', name='businesstype'), nullable=False),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('contact_phone', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('created_by', GUID(), nullable=False),
    sa.Column('last_modified_by', GUID(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['last_modified_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_channels_business_type'), 'channels', ['business_type'], unique=False)
    op.create_index(op.f('ix_channels_created_at'), 'channels', ['created_at'], unique=False)
    op.create_index(op.f('ix_channels_name'), 'channels', ['name'], unique=True)
    op.create_index(op.f('ix_channels_status'), 'channels', ['status'], unique=False)
    op.create_table('channel_assignments',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('user_id', GUID(), nullable=False),
    sa.Column('channel_id', GUID(), nullable=False),
    sa.Column('permission_level', sa.Enum('read', 'write', 'admin', name='permissionlevel'), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('assigned_by', GUID(), nullable=False),
    sa.Column('target_responsibility', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'channel_id', name='uix_user_channel')
    )
    op.create_table('channel_targets',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('channel_id', GUID(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('quarter', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=True),
    sa.Column('performance_target', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('opportunity_target', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('project_count_target', sa.Integer(), nullable=True),
    sa.Column('development_goal', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('created_by', GUID(), nullable=False),
    sa.Column('achieved_performance', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('achieved_opportunity', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('achieved_project_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('channel_id', 'year', 'quarter', 'month', name='uix_channel_period')
    )
    op.create_index(op.f('ix_channel_targets_channel_id'), 'channel_targets', ['channel_id'], unique=False)
    op.create_index(op.f('ix_channel_targets_month'), 'channel_targets', ['month'], unique=False)
    op.create_index(op.f('ix_channel_targets_quarter'), 'channel_targets', ['quarter'], unique=False)
    op.create_index(op.f('ix_channel_targets_year'), 'channel_targets', ['year'], unique=False)
    op.create_table('execution_plans',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('channel_id', GUID(), nullable=False),
    sa.Column('user_id', GUID(), nullable=False),
    sa.Column('plan_type', sa.Enum('monthly', 'weekly', name='plantype'), nullable=False),
    sa.Column('plan_period', sa.String(length=20), nullable=False),
    sa.Column('plan_content', sa.Text(), nullable=False),
    sa.Column('execution_status', sa.Text(), nullable=True),
    sa.Column('key_obstacles', sa.Text(), nullable=True),
    sa.Column('next_steps', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('status', sa.Enum('planned', 'in_progress', 'completed', 'archived', name='executionstatus'), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_execution_plans_channel_id'), 'execution_plans', ['channel_id'], unique=False)
    op.create_index(op.f('ix_execution_plans_plan_period'), 'execution_plans', ['plan_period'], unique=False)
    op.create_index(op.f('ix_execution_plans_plan_type'), 'execution_plans', ['plan_type'], unique=False)
    op.create_index(op.f('ix_execution_plans_status'), 'execution_plans', ['status'], unique=False)
    op.create_index(op.f('ix_execution_plans_user_id'), 'execution_plans', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_execution_plans_user_id'), table_name='execution_plans')
    op.drop_index(op.f('ix_execution_plans_status'), table_name='execution_plans')
    op.drop_index(op.f('ix_execution_plans_plan_type'), table_name='execution_plans')
    op.drop_index(op.f('ix_execution_plans_plan_period'), table_name='execution_plans')
    op.drop_index(op.f('ix_execution_plans_channel_id'), table_name='execution_plans')
    op.drop_table('execution_plans')
    op.drop_index(op.f('ix_channel_targets_year'), table_name='channel_targets')
    op.drop_index(op.f('ix_channel_targets_quarter'), table_name='channel_targets')
    op.drop_index(op.f('ix_channel_targets_month'), table_name='channel_targets')
    op.drop_index(op.f('ix_channel_targets_channel_id'), table_name='channel_targets')
    op.drop_table('channel_targets')
    op.drop_table('channel_assignments')
    op.drop_index(op.f('ix_channels_status'), table_name='channels')
    op.drop_index(op.f('ix_channels_name'), table_name='channels')
    op.drop_index(op.f('ix_channels_created_at'), table_name='channels')
    op.drop_index(op.f('ix_channels_business_type'), table_name='channels')
    op.drop_table('channels')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
