"""create unified_targets table

Revision ID: 211261ca3f2b
Revises: d3a8cc08b2e8
Create Date: 2025-10-15 14:48:44.901118

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from src.database import GUID


# revision identifiers, used by Alembic.
revision: str = '211261ca3f2b'
down_revision: Union[str, None] = 'd3a8cc08b2e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Drop deprecated person_channel_targets table before creating unified_targets
    # This is a refactoring - the new unified_targets replaces person_channel_targets
    op.drop_table('person_channel_targets')

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('unified_targets',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('target_type', sa.Enum('person', 'channel', name='targettype'), nullable=False),
    sa.Column('target_id', GUID(), nullable=False),
    sa.Column('period_type', sa.Enum('quarter', 'month', name='periodtype'), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('quarter', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=True),
    sa.Column('new_signing_target', sa.Integer(), nullable=False),
    sa.Column('core_opportunity_target', sa.Integer(), nullable=False),
    sa.Column('core_performance_target', sa.Integer(), nullable=False),
    sa.Column('high_value_opportunity_target', sa.Integer(), nullable=False),
    sa.Column('high_value_performance_target', sa.Integer(), nullable=False),
    sa.Column('new_signing_achieved', sa.Integer(), nullable=False),
    sa.Column('core_opportunity_achieved', sa.Integer(), nullable=False),
    sa.Column('core_performance_achieved', sa.Integer(), nullable=False),
    sa.Column('high_value_opportunity_achieved', sa.Integer(), nullable=False),
    sa.Column('high_value_performance_achieved', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('created_by', GUID(), nullable=False),
    sa.Column('last_modified_by', GUID(), nullable=False),
    sa.CheckConstraint("(period_type = 'quarter' AND month IS NULL) OR (period_type = 'month' AND month IS NOT NULL)", name='chk_period_consistency'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['last_modified_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('target_type', 'target_id', 'period_type', 'year', 'quarter', 'month', name='uix_target_period')
    )
    op.create_index(op.f('ix_unified_targets_created_at'), 'unified_targets', ['created_at'], unique=False)
    op.create_index(op.f('ix_unified_targets_month'), 'unified_targets', ['month'], unique=False)
    op.create_index(op.f('ix_unified_targets_period_type'), 'unified_targets', ['period_type'], unique=False)
    op.create_index(op.f('ix_unified_targets_quarter'), 'unified_targets', ['quarter'], unique=False)
    op.create_index(op.f('ix_unified_targets_target_id'), 'unified_targets', ['target_id'], unique=False)
    op.create_index(op.f('ix_unified_targets_target_type'), 'unified_targets', ['target_type'], unique=False)
    op.create_index(op.f('ix_unified_targets_year'), 'unified_targets', ['year'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_unified_targets_year'), table_name='unified_targets')
    op.drop_index(op.f('ix_unified_targets_target_type'), table_name='unified_targets')
    op.drop_index(op.f('ix_unified_targets_target_id'), table_name='unified_targets')
    op.drop_index(op.f('ix_unified_targets_quarter'), table_name='unified_targets')
    op.drop_index(op.f('ix_unified_targets_period_type'), table_name='unified_targets')
    op.drop_index(op.f('ix_unified_targets_month'), table_name='unified_targets')
    op.drop_index(op.f('ix_unified_targets_created_at'), table_name='unified_targets')
    op.drop_table('unified_targets')
    # ### end Alembic commands ###
