"""Add indexes to channel_assignments table

Revision ID: 7352e85b6891
Revises: 480e18c0374d
Create Date: 2025-10-14 10:44:25.040491

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7352e85b6891'
down_revision: Union[str, None] = '480e18c0374d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_channel_assignments_assigned_at'), 'channel_assignments', ['assigned_at'], unique=False)
    op.create_index(op.f('ix_channel_assignments_assigned_by'), 'channel_assignments', ['assigned_by'], unique=False)
    op.create_index(op.f('ix_channel_assignments_channel_id'), 'channel_assignments', ['channel_id'], unique=False)
    op.create_index(op.f('ix_channel_assignments_permission_level'), 'channel_assignments', ['permission_level'], unique=False)
    op.create_index(op.f('ix_channel_assignments_user_id'), 'channel_assignments', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_channel_assignments_user_id'), table_name='channel_assignments')
    op.drop_index(op.f('ix_channel_assignments_permission_level'), table_name='channel_assignments')
    op.drop_index(op.f('ix_channel_assignments_channel_id'), table_name='channel_assignments')
    op.drop_index(op.f('ix_channel_assignments_assigned_by'), table_name='channel_assignments')
    op.drop_index(op.f('ix_channel_assignments_assigned_at'), table_name='channel_assignments')
    # ### end Alembic commands ###
