"""add_person_channel_targets_table

Revision ID: d3a8cc08b2e8
Revises: abf0f3fe94d9
Create Date: 2025-10-15 14:04:29.855964

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import UUID

from src.database import GUID


# revision identifiers, used by Alembic.
revision: str = 'd3a8cc08b2e8'
down_revision: Union[str, None] = 'abf0f3fe94d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('person_channel_targets',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('target_type', sa.Enum('person', 'channel', name='targettype'), nullable=False),
    sa.Column('target_id', GUID(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('quarter', sa.Integer(), nullable=False),
    sa.Column('quarter_new_signing', sa.Integer(), nullable=True),
    sa.Column('quarter_core_opportunity', sa.Integer(), nullable=True),
    sa.Column('quarter_core_performance', sa.Integer(), nullable=True),
    sa.Column('quarter_high_value_opportunity', sa.Integer(), nullable=True),
    sa.Column('quarter_high_value_performance', sa.Integer(), nullable=True),
    sa.Column('month_targets', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('created_by', GUID(), nullable=False),
    sa.Column('last_modified_by', GUID(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['last_modified_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('target_type', 'target_id', 'year', 'quarter', name='uix_target_period')
    )
    op.create_index(op.f('ix_person_channel_targets_created_at'), 'person_channel_targets', ['created_at'], unique=False)
    op.create_index(op.f('ix_person_channel_targets_quarter'), 'person_channel_targets', ['quarter'], unique=False)
    op.create_index(op.f('ix_person_channel_targets_target_id'), 'person_channel_targets', ['target_id'], unique=False)
    op.create_index(op.f('ix_person_channel_targets_target_type'), 'person_channel_targets', ['target_type'], unique=False)
    op.create_index(op.f('ix_person_channel_targets_year'), 'person_channel_targets', ['year'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_person_channel_targets_year'), table_name='person_channel_targets')
    op.drop_index(op.f('ix_person_channel_targets_target_type'), table_name='person_channel_targets')
    op.drop_index(op.f('ix_person_channel_targets_target_id'), table_name='person_channel_targets')
    op.drop_index(op.f('ix_person_channel_targets_quarter'), table_name='person_channel_targets')
    op.drop_index(op.f('ix_person_channel_targets_created_at'), table_name='person_channel_targets')
    op.drop_table('person_channel_targets')
    # ### end Alembic commands ###
