export const regionMap: Record<string, string> = {
  'Shandong': '山东',
  'Jinan': '济南',
  'Qingdao': '青岛',
  'Zibo': '淄博',
  'Zaozhuang': '枣庄',
  'Dongying': '东营',
  'Yantai': '烟台',
  'Weifang': '潍坊',
  'Jining': '济宁',
  'Taian': '泰安',
  'Weihai': '威海',
  'Rizhao': '日照',
  'Linyi': '临沂',
  'Dezhou': '德州',
  'Liaocheng': '聊城',
  'Binzhou': '滨州',
  'Heze': '菏泽',
  'Lixia': '历下区',
  'Shizhong': '市中区',
  'Huaiyin': '槐荫区',
  'Tianqiao': '天桥区',
  'Licheng': '历城区',
  'Changqing': '长清区',
  'Shinan': '市南区',
  'Shibei': '市北区',
  'Huangdao': '黄岛区',
  'Laoshan': '崂山区',
  'Licang': '李沧区',
  'Chengyang': '城阳区',
  'Jimo': '即墨区',
  'Zhangdian': '张店区',
  'Zichuan': '淄川区',
  'Boshan': '博山区',
  'Linzi': '临淄区',
  'Zhoucun': '周村区',
  'Xuecheng': '薛城区',
  'Yicheng': '峄城区',
  'Taierzhuang': '台儿庄区',
  'Shanting': '山亭区',
  'Hekou': '河口区',
  'Kenli': '垦利区',
  'Zhifu': '芝罘区',
  'Fushan': '福山区',
  'Muping': '牟平区',
  'Laishan': '莱山区',
  'Penglai': '蓬莱区',
  'Kuiwen': '奎文区',
  'Weicheng': '潍城区',
  'Hanting': '寒亭区',
  'Fangzi': '坊子区',
  'Rencheng': '任城区',
  'Yanzhou': '兖州区',
  'Qufu': '曲阜市',
  'Taishan': '泰山区',
  'Daiyue': '岱岳区',
  'Huancui': '环翠区',
  'Wendeng': '文登区',
  'Rongcheng': '荣成市',
  'Donggang': '东港区',
  'Lanshan': '岚山区',
  'Luozhuang': '罗庄区',
  'Hedong': '河东区',
  'Decheng': '德城区',
  'Lingcheng': '陵城区',
  'Dongchangfu': '东昌府区',
  'Chiping': '茌平区',
  'Bincheng': '滨城区',
  'Zhanhua': '沾化区',
  'Mudan': '牡丹区',
  'Dingtao': '定陶区',
}

export function formatRegion(region: string): string {
  if (!region) return ''
  return region
    .split('/')
    .map(part => regionMap[part] || part)
    .join('/')
}
